=encoding utf8

=head1 NAME

Guides - Yoyakku guide to the galaxy

音楽スタジオ予約 WEB アプリケーションの案内

=head1 REFERENCE

This is the class hierarchy of the Yoyakku distribution.

=head1 DIRECTORY

    Yoyakku                 # アプリケーションディレクトリ
    |- db                   # データベースファイルディレクトリ
    |- lib                  # ライブラリディレクトリ
    |- local                # モジュールディレクトリ
    |- public               # 静的なファイルのディレクトリ
    |- script               # スクリプトディレクトリ
    |- sql                  # SQLファイルディレクトリ
    |- t                    # テストコードディレクトリ
    |- templates            # テンプレートディレクトリ
    |- .gitignore           # git履歴除外
    |- .perl-version        # Perlバージョン指定
    |- cpanfile             # インストールモジュールリスト
    |- cpanfile.snapshot    # インストールモジュール履歴
    |- Guides.pod           # ドキュメント一覧
    +- README.md            # はじめに読むべきファイル

yoyakku アプリケーション全体のディレクトリ構成

=head2 DIRECTORY DB

    db                # データベースファイルディレクトリ
    +- yoyakku.db     # SQLite3 データベースファイル

データベースファイルディレクトリ構成

    DATABASE yoyakku

    TABLES

    region:     地域区分マスタ
    storeinfo:  店舗情報
    roominfo:   部屋情報設定
    reserve:    予約履歴
    ads:        広告
    admin:      管理ユーザー
    general:    一般ユーザー
    profile:    個人情報
    acting:     代行リスト
    mailbox:    メール配信用データ
    post:       郵便番号マスタ

    + - - - - - - - +
    |   storeinfo   |
    + - + - + - + - +
    |   |   |   |   |
    |   |   |   |   + roominfo
    |   |   |   |       |
    |   |   |   |       + reserve
    |   |   |   |           |   |
    |   |   |   |           |   + - - - - - - - +
    |   |   |   |           |                   |
    |   |   |   |           + general           |
    |   |   |   |               |   |           |
    |   |   |   |   + - - - - - +   + profile   |
    |   |   |   |   |                   |       |
    |   |   |   + acting                |       |
    |   |   |                           |       |
    |   |   |   + - - - - - - - - - - - +       |
    |   |   |   |                               |
    |   |   |   |   + - - - - - - - - - - - - - +
    |   |   |   |   |
    |   |   + admin +
    |   |
    |   + ads
    |       |
    |   + - +
    |   |
    + region

yoyakku アプリケーションのデータベース構成

=head2 DIRECTORY LIB

    lib               # ライブラリディレクトリ
    |- Yoyakku        # アプリケーション名前空間
    |  |- Controller  # コントローラー名前空間
    |  |- Model       # モデル名前空間
    |  |- Model.pm    # モデルクラス
    |  +- Util.pm     # ユーティリティークラス
    +- Yoyakku.pm     # アプリケーションクラス

=over 1

=item Yoyakku

=over 2

=item Controller

=over 3

=item Mainte

=over 4

=item L<Yoyakku::Controller::Mainte::Acting>

=item L<Yoyakku::Controller::Mainte::Admin>

=item L<Yoyakku::Controller::Mainte::Ads>

=item L<Yoyakku::Controller::Mainte::General>

=item L<Yoyakku::Controller::Mainte::Profile>

=item L<Yoyakku::Controller::Mainte::Roominfo>

=item L<Yoyakku::Controller::Mainte::Storeinfo>

=back

=item L<Yoyakku::Controller::Auth>

=item L<Yoyakku::Controller::Calendar>

=item L<Yoyakku::Controller::Mainte>

=item L<Yoyakku::Controller::Profile>

=back

=item Model

=over 3

=item Mainte

=over 4

=item L<Yoyakku::Model::Mainte::Acting>

=item L<Yoyakku::Model::Mainte::Admin>

=item L<Yoyakku::Model::Mainte::Ads>

=item L<Yoyakku::Model::Mainte::General>

=item L<Yoyakku::Model::Mainte::Profile>

=item L<Yoyakku::Model::Mainte::Roominfo>

=item L<Yoyakku::Model::Mainte::Storeinfo>

=back

=item L<Yoyakku::Model::Auth>

=item L<Yoyakku::Model::Calendar>

=item L<Yoyakku::Model::Mainte>

=item L<Yoyakku::Model::Profile>

=back

=item L<Yoyakku::Master>

=item L<Yoyakku::Model>

=item L<Yoyakku::Util>

=back

=item L<Yoyakku>

=back

ライブラリディレクトリ構成

=head2 DIRECTORY LOCAL

    |- local    # モジュールディレクトリ

モジュールディレクトリ構成

=head2 DIRECTORY PUBLIC

    |- public   # 静的なファイルのディレクトリ

静的なファイルのディレクトリ構成

=head2 DIRECTORY SCRIPT

    script      # スクリプトディレクトリ
    +- yoyakku  # アプリケーションスクリプト

    # 起動するファイル、起動のコマンドなどはファイルドキュメント参照

=over

=item L<script::yoyakku>

=back

スクリプトディレクトリ構成

=head2 DIRECTORY SQL

    sql             # SQLファイルディレクトリ
    +- sqlite.sql   # SQLite 用スキーマー構築 SQL ファイル

SQLファイルディレクトリ構成

=head2 DIRECTORY T

    t           # テストコードディレクトリ
    +- basic.t  # 基本テスト

テストコードディレクトリ構成

=head2 DIRECTORY TEMPLATES

    |- templates    # テンプレートディレクトリ

テンプレートディレクトリ構成
